# Generated by Django 5.1.1 on 2024-10-07 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NCCVai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ncc', models.CharField(max_length=10, unique=True)),
                ('ten_ncc', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('dia_chi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NVL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vai', models.CharField(max_length=10, unique=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='nvl_images/')),
                ('ten_vai', models.CharField(max_length=255)),
                ('don_vi_tinh', models.CharField(max_length=50)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat_hang', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(default='Đang xử lý', max_length=50)),
                ('ncc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.nccvai')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('nvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.nvl')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='KhoNVL.order')),
            ],
        ),
    ]
