# Generated by Django 5.1.1 on 2024-10-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0002_alter_nccvai_id_ncc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nvl',
            name='id_vai',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
