# Generated by Django 5.1.1 on 2024-10-14 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0003_alter_nvl_id_vai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nvl',
            name='gia',
        ),
        migrations.AddField(
            model_name='order',
            name='phi_van_chuyen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='thue_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GiaNCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ncc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.nccvai')),
                ('nvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.nvl')),
            ],
            options={
                'unique_together': {('ncc', 'nvl')},
            },
        ),
    ]
