# Generated by Django 5.1.1 on 2024-10-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0004_remove_nvl_gia_order_phi_van_chuyen_order_thue_vat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='gia',
        ),
    ]
