# Generated by Django 5.1.1 on 2024-10-14 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0005_remove_orderitem_gia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_tri', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_ton', models.PositiveIntegerField(default=0)),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.kho')),
                ('ncc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.nccvai')),
                ('nvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.nvl')),
            ],
            options={
                'unique_together': {('nvl', 'ncc', 'kho')},
            },
        ),
    ]
