# Generated by Django 5.1.1 on 2024-10-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0008_alter_tonkho_unique_together_tonkho_vi_tri_kho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XuatNVL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_xuat', models.PositiveIntegerField()),
                ('ngay_xuat', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.nvl')),
                ('vi_tri_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.tonkho')),
            ],
        ),
    ]
