# Generated by Django 5.1.1 on 2024-10-20 07:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0010_xuatkho_xuatkhoitem_delete_xuatnvl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_thanh_pham', models.CharField(blank=True, max_length=10, unique=True)),
                ('ten_thanh_pham', models.CharField(max_length=255)),
                ('mau_sac', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='nvl',
            name='mau_sac',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xuatkho',
            name='thanh_pham',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.thanhpham'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ThanhPhamNVL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_can', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('nvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanhpham_nguyenlieu', to='KhoNVL.nvl')),
                ('thanh_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguyen_vat_lieu', to='KhoNVL.thanhpham')),
            ],
        ),
    ]
