# Generated by Django 5.1.1 on 2024-10-20 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0011_thanhpham_nvl_mau_sac_xuatkho_thanh_pham_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvl',
            name='nha_cung_cap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.nccvai'),
            preserve_default=False,
        ),
    ]
