# Generated by Django 5.1.1 on 2024-10-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0012_nvl_nha_cung_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvl',
            name='so_luong_ton',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
