# Generated by Django 5.1.1 on 2024-10-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0015_remove_xuatkhoitem_xuat_kho_remove_xuatkhoitem_nvl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TonKho',
        ),
    ]
