# Generated by Django 5.1.1 on 2024-10-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0017_xuatkho_xuatkhoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xuatkho',
            name='thanh_pham',
        ),
    ]
