# Generated by Django 5.1.1 on 2024-10-26 15:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0019_xuatkho_thanh_phams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xuatkho',
            name='thanh_phams',
        ),
        migrations.RemoveField(
            model_name='xuatkhoitem',
            name='nvl',
        ),
        migrations.RemoveField(
            model_name='xuatkhoitem',
            name='so_luong_xuat',
        ),
        migrations.RemoveField(
            model_name='xuatkhoitem',
            name='vai_tro',
        ),
        migrations.AddField(
            model_name='xuatkhoitem',
            name='so_luong_thanh_pham',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='xuatkhoitem',
            name='thanh_pham',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.thanhpham'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thanhphamnvl',
            name='vai_tro',
            field=models.CharField(choices=[('Vải Chính', 'Vải chính'), ('Vải Lót', 'Vải lót')], max_length=10),
        ),
        migrations.CreateModel(
            name='XuatKhoNVL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_xuat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vai_tro', models.CharField(choices=[('Chính', 'Vải chính'), ('Lót', 'Vải lót')], max_length=10)),
                ('nvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.nvl')),
                ('xuat_kho_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nvl_xuat', to='KhoNVL.xuatkhoitem')),
            ],
        ),
    ]
