# Generated by Django 5.1.1 on 2024-10-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0020_remove_xuatkho_thanh_phams_remove_xuatkhoitem_nvl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuatkhoitem',
            name='loai_san_pham',
            field=models.CharField(choices=[('May Thành Phẩm', 'May Thành Phẩm'), ('May Mẫu', 'May Mẫu')], default='May Thành Phẩm', max_length=20),
        ),
    ]
