# Generated by Django 5.1.1 on 2024-10-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0021_xuatkhoitem_loai_san_pham'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuatkho',
            name='trang_thai',
            field=models.CharField(default='Đang xử lý', max_length=50),
        ),
    ]
