# Generated by Django 5.1.1 on 2024-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0022_xuatkho_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanhpham',
            name='so_luong_ton',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xuatkhonvl',
            name='vai_tro',
            field=models.CharField(choices=[('Vải Chính', 'Vải chính'), ('Vải Lót', 'Vải lót')], max_length=10),
        ),
    ]
