# Generated by Django 5.1.1 on 2024-10-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0024_thanhpham_don_gia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kho',
        ),
    ]
