# Generated by Django 5.1.1 on 2024-11-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0025_delete_kho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ncc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phi_van_chuyen',
        ),
        migrations.RemoveField(
            model_name='order',
            name='thue_vat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trang_thai',
        ),
    ]
