# Generated by Django 5.1.1 on 2024-11-10 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0027_dotkiemkho_kiemkhoitem'),
        ('KhoThanhPham', '0012_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xuat', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='xuatkhoitem',
            name='xuat_kho',
        ),
        migrations.RemoveField(
            model_name='xuatkhonvl',
            name='nvl',
        ),
        migrations.RemoveField(
            model_name='xuatkhonvl',
            name='xuat_kho_item',
        ),
        migrations.RemoveField(
            model_name='xuatkhoitem',
            name='loai_san_pham',
        ),
        migrations.RemoveField(
            model_name='xuatkhoitem',
            name='so_luong_thanh_pham',
        ),
        migrations.RemoveField(
            model_name='xuatkhoitem',
            name='thanh_pham',
        ),
        migrations.AddField(
            model_name='xuatkhoitem',
            name='nvl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.nvl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xuatkhoitem',
            name='so_luong_xuat',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xuatkhoitem',
            name='dot_xuat_kho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='KhoNVL.dotxuatkho'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='XuatKho',
        ),
        migrations.DeleteModel(
            name='XuatKhoNVL',
        ),
    ]
