# Generated by Django 5.1.1 on 2024-10-20 06:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoThanhPham', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanhphamnvl',
            name='so_luong_can',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
