# Generated by Django 5.1.1 on 2024-10-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoThanhPham', '0002_alter_thanhphamnvl_so_luong_can'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanhpham',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=3),
        ),
    ]
