# Generated by Django 5.1.1 on 2024-10-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhoThanhPham', '0003_alter_thanhpham_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanhphamnvl',
            name='thanh_pham',
        ),
        migrations.RemoveField(
            model_name='thanhphamnvl',
            name='nvl',
        ),
        migrations.DeleteModel(
            name='ThanhPham',
        ),
        migrations.DeleteModel(
            name='ThanhPhamNVL',
        ),
    ]
