# Generated by Django 5.1.1 on 2024-10-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoThanhPham', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhapkhothanhpham',
            name='trang_thai',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('waiting_for_production', 'Chờ sản xuất')], default='pending', max_length=50),
        ),
    ]
