# Generated by Django 5.1.1 on 2024-10-28 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoThanhPham', '0007_customer_order_orderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trang_thai',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KhoThanhPham.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='so_luong',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
