# Generated by Django 5.1.1 on 2024-10-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhoThanhPham', '0008_remove_order_trang_thai_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='don_gia',
        ),
    ]
