# Generated by Django 5.1.1 on 2024-10-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhoThanhPham', '0009_remove_orderline_don_gia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tong_tien',
        ),
    ]
