# Generated by Django 5.1.1 on 2024-11-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhoThanhPham', '0011_order_tong_tien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='nhapkhothanhpham',
            name='xuat_kho',
        ),
        migrations.RemoveField(
            model_name='nhapkhothanhphamitem',
            name='nhap_kho',
        ),
        migrations.RemoveField(
            model_name='nhapkhothanhphamitem',
            name='thanh_pham',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='thanh_pham',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='NhapKhoThanhPham',
        ),
        migrations.DeleteModel(
            name='NhapKhoThanhPhamItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
    ]
