# Generated by Django 5.1.1 on 2024-11-10 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0028_dotxuatkho_remove_xuatkhoitem_xuat_kho_and_more'),
        ('KhoThanhPham', '0013_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XuatKhoThanhPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xuat', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XuatKhoThanhPhamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('thanh_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.thanhpham')),
                ('xuat_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='KhoThanhPham.xuatkhothanhpham')),
            ],
        ),
    ]
