# Generated by Django 5.1.1 on 2024-11-10 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhoNVL', '0028_dotxuatkho_remove_xuatkhoitem_xuat_kho_and_more'),
        ('KhoThanhPham', '0014_xuatkhothanhpham_xuatkhothanhphamitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='KiemKhoThanhPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kiem', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KiemKhoThanhPhamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_ly_thuyet', models.PositiveIntegerField()),
                ('so_luong_thuc_te', models.PositiveIntegerField()),
                ('so_luong_chenh_lech', models.IntegerField(blank=True, null=True)),
                ('kiem_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='KhoThanhPham.kiemkhothanhpham')),
                ('thanh_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KhoNVL.thanhpham')),
            ],
        ),
    ]
